version: '3.8'
services:
  e2e-tests-chrome:
    build: .
    container_name: cypress_e2e_tests_chrome
    command: /bin/bash -c "/usr/local/bin/verify-cypress.sh && npx cypress run --headless --browser chrome"
    volumes:
      - ./:/app
      - ./cypress/screenshots:/app/cypress/screenshots/chrome
      - ./cypress/videos:/app/cypress/videos/chrome
    environment:
      - DISPLAY=
      - TEST_ENV=${TEST_ENV}
      - VIEWPORT_WIDTH=${VIEWPORT_WIDTH}
      - VIEWPORT_HEIGHT=${VIEWPORT_HEIGHT}
      - TEST_BROWSER=chrome
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  e2e-tests-firefox:
    build: .
    container_name: cypress_e2e_tests_firefox
    command: /bin/bash -c "/usr/local/bin/verify-cypress.sh && npx cypress run --headless --browser firefox"
    volumes:
      - ./:/app
      - ./cypress/screenshots:/app/cypress/screenshots/firefox
      - ./cypress/videos:/app/cypress/videos/firefox
    environment:
      - DISPLAY=
      - TEST_ENV=${TEST_ENV}
      - VIEWPORT_WIDTH=${VIEWPORT_WIDTH}
      - VIEWPORT_HEIGHT=${VIEWPORT_HEIGHT}
      - TEST_BROWSER=firefox
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
