version: '3.8'
services:
  e2e-tests:
    build: .
    container_name: cypress_e2e_tests
    command: /bin/bash -c "/usr/local/bin/verify-cypress.sh && npx cypress run --headless --browser electron"
    volumes:
      - ./:/app
      - ./cypress/screenshots:/app/cypress/screenshots
      - ./cypress/videos:/app/cypress/videos
    environment:
      - DISPLAY=
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
